# possible_answer_models.py - Pydantic Models for Possible Answer Feature
# ============================================================================

from pydantic import BaseModel, Field


class RawPDFContent(BaseModel):
    """Raw PDF content with page structure."""
    filename: str = Field(description="PDF filename")
    pages: list[tuple[int, str]] = Field(
        default_factory=list,
        description="List of (page_number, text) tuples"
    )
    total_pages: int = Field(default=0, description="Total number of pages")
    total_characters: int = Field(default=0, description="Total character count")


class TextSegment(BaseModel):
    """A segment of text for LLM processing."""
    text: str = Field(description="Text content")
    start_page: int = Field(description="Starting page number")
    end_page: int = Field(description="Ending page number")
    estimated_tokens: int = Field(default=0, description="Estimated token count")


class PossibleAnswer(BaseModel):
    """A possible answer generated by LLM from raw PDF."""
    criterion: str = Field(description="The audit criterion")
    answer: str = Field(default="", description="Generated possible answer text")
    relevant_pages: list[int] = Field(
        default_factory=list,
        description="Pages where info was found"
    )
    found: bool = Field(default=False, description="Whether relevant information was found")


class PossibleAnswerConfig(BaseModel):
    """Configuration for possible answer feature."""
    enabled: bool = Field(default=False, description="Enable possible answer generation")
